# Generated by Django 5.0.2 on 2024-02-20 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genius', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draft',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='draftpage',
            old_name='draftId',
            new_name='draft',
        ),
        migrations.RenameField(
            model_name='draftpage',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='draftId',
            new_name='draft',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='followers',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='intro',
            old_name='draftId',
            new_name='draft',
        ),
        migrations.RenameField(
            model_name='intro',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='myflower',
            old_name='flowerId',
            new_name='flower',
        ),
        migrations.RenameField(
            model_name='myflower',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='myforest',
            old_name='flowerId',
            new_name='flower',
        ),
        migrations.RenameField(
            model_name='myforest',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='mylibrary',
            old_name='bookId',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='mylibrary',
            old_name='userId',
            new_name='user',
        ),
    ]
